### ISSUE TITLE
Does `-u` work? 

### ISSUE THREAD

**Issue by basarat** [svtek/g3l#4]
I don't see `program.update` being handled anywhere like other things (e.g. `program.enable`: https://github.com/svtek/g3l/blob/25454ea93885dabd90b0036f161111d9d3f075f6/index.js#L50). 

I suspect its not implemented yet?. Thanks in advance! :rose: 

> Sorry for the intrusion, I would like something like that for alm http://alm.tools/ and hoping to learn from you if you have it done :heart:

**Comment by cagataycali** [comment]
Hi Basarat, 
program.enable handled with their short usage. Example; 
g3l -m "awesome commit" -b new/featureBranch -p

That command will work in their priority.
Thanks for your interest 👍

**Comment by basarat** [comment]
^ Sorry. Perhaps I was unclear. I want to know how `program.update` is handled :rose:

**Comment by cagataycali** [comment]
I'll explain in step by step 👍 
- Firstly process.args parsed with commander npm package
  https://github.com/svtek/g3l/blob/master/index.js#L33
- Secondly commands array reversed by priority
  https://github.com/svtek/g3l/blob/master/index.js#L83 , https://github.com/svtek/g3l/blob/master/index.js#L195
- Then called run function in code
  https://github.com/svtek/g3l/blob/master/index.js#L173
- The eval command checks if that arg handled successfully
  https://github.com/svtek/g3l/blob/master/index.js#L176
- Then again run their function in their priority queue
  https://github.com/svtek/g3l/blob/master/index.js#L179

I hope clarify your ideas 👍

**Comment by cagataycali** [comment]
There was an error, I already fixed in new version.
g3l -u working in
g3l@10.0.7
💯

**Comment by basarat** [comment]
Awesome, thanks for the detailed explanation. Got the code I was looking for too :rose: :heart: https://github.com/svtek/g3l/blob/fabe9865ff06c7ca87ae500ea27186d7abd48918/index.js#L262-L275

That said, I suspect it will not work on windows as `g3l` will be executing when `npm i -g g3l` will run and npm will not be able to unlink the installation path folder. But that can go in a seperate issue if that happens / gets reported. Thanks again for your awesome work + help 👏 🚀 :rose:

**Comment by cagataycali** [comment]
I didn't try g3l -u on windows yet, thanks for your advice. I'll try this command on windows machine  
as soon as possible 💯
